Traceback (most recent call last):
  File "C:/Users/pc/Documents/Automated the boring stuff/chapter 11/tracback error.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
